### ISSUE TITLE
Scoping Floating Button and demo/prototype

### ISSUE THREAD

**Issue by agonza1** [voxbone-workshop/click2vox-com#651]
Easier way for customers to use the widget by just copy&paste a <script> tag with default css styling.

Attach scope/project plan.

**Sub-task from #589**

**Comment by agonza1** [comment]
## **SCOPING FLOATING BUTTON**

MINIMUM VIABLE FEATURE, FLOATING BUTTON with option to choose button location AND non-available in the click2vox UI (estimate 2 - 3 )

### _Approach 1:_ 
Data tags adding something like data-floating="true" we would render floating, otherwise the default button. The widget would have the same view.

### _Approach 2:_
Using JS instead of html to declare the variables to be sent to click2vox. The logic in click2vox would be the same that approach 1 and 
would be a non-breaking change. Customer could use this approach or the old one. 
E.g apporach 2:
<script>
 var voxConfig = {
 button_id: "585c36b46e5b48110063b22f",
 text: "Call Us",
 did: "883510080361",
 div_css_class_name: 'style-a'
};</script>
<div class="voxButton voxFloating"></div>
<script async="async" src='http://localhost:3000/click2vox.js'></script>


Or a variant of the previous approach using a function:
  <script>
   var voxButtonElements;
      function initVoxButton() {
        voxButtonElements = {
        button_id: "585c36b46e5b48110063b22f",
        text: "Call Us",
        did: "883510080361",
        div_css_class_name: 'style-a'
        };
      }
</script>



_Other ideas/opinions?_ 

### _For the location of the widget:_

We could use the same methodology than the one used for the current widget:
User snippet contains `button-placement=bottom-right` and we add the vw-bottom-right to the button class if floating button

Do we have CSS for the floating circular and rectangular style? It should include the positions we want the floating button and we should take care not to cover the widget with the floating button.

## **SCOPE FULL ISSUE/FEATURE #589**

backend click2vox floating button (3)

CSS styling (?)

front end click2vox (2)

TBC

**Comment by fikrifirat** [comment]
@agonza1 A note on location of the widget
What will happen to the button when the call starts? Does it make sense to show button and the widget (call container) in different locations? What happens when the customer wants to show both of them in the same area?

I see two approaches here :
1. We make the customer choose both widget and button locations separately. In this case, we should hide the button when the call starts and show it back when it ends or call container is destroyed.

2. By default widget (call container) and the button location is tied to one single tag, and appear at the same location. In this case, we should again hide the button when the cal starts and show it back when the call ends or call container gets destroyed.

**Comment by agonza1** [comment]
@fikrifirat Yes, you are right I think we shouldn't display both. I think the 2nd approac would be better as we would be using one variable less

**Comment by agonza1** [comment]
Moving to click2vox SDK #695

**Comment by agonza1** [comment]
SCOPE:
- [ ] Initialization of `var click2vox = {did: "1234"...}` displaying the floating button if there isn't any voxbutton <div> already in the document
- [ ] Adding styling for the floating button (1)
- [ ] Functionality hide/show button when widget appears. (0.5)
- [ ] Button style/configuration will be passed as in the old button but through javascript. E.g: `var click2vox = {placement: "top-right"...}` (0.5)
- [ ] Display this option/feature in the click2vox site? (2)
- [ ] Documentation (1)

Estimate 5.
